//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRays
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public long BranchId { get; set; }
        public long Branch_Code { get; set; }
        public string BranchName { get; set; }
        public System.DateTime Last_Modified_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
        public long Last_Modified_User { get; set; }
        public int IsDeleted { get; set; }
    }
}
