//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRays
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmployeeId { get; set; }
        public long Employee_Code { get; set; }
        public string EmployeeName { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string LandLine { get; set; }
        public string Email { get; set; }
        public string National_Id { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeAddress2 { get; set; }
        public System.DateTime Birthdate { get; set; }
        public System.DateTime HiringDate { get; set; }
        public int Gender_Id { get; set; }
        public int Natinality_Code { get; set; }
        public long Job_Code { get; set; }
        public long Branch_Code { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public Nullable<long> Last_Modified_User { get; set; }
        public int IsDeleted { get; set; }
        public int Created_User { get; set; }
    }
}
