//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRays
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_View
    {
        public string National_Name { get; set; }
        public string Gender_Name { get; set; }
        public string BranchName { get; set; }
        public string DepartmentName { get; set; }
        public string JobName { get; set; }
        public long Employee_Code { get; set; }
        public string EmployeeName { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string LandLine { get; set; }
        public string Email { get; set; }
        public string National_Id { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeAddress2 { get; set; }
        public System.DateTime Birthdate { get; set; }
        public System.DateTime HiringDate { get; set; }
        public int IsDeleted { get; set; }
    }
}
