//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRays
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EndSalaries = new HashSet<EndSalary>();
            this.Salaries = new HashSet<Salary>();
            this.SalaryTransactions = new HashSet<SalaryTransaction>();
        }
    
        public long EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string LandLine { get; set; }
        public string Email { get; set; }
        public string National_Id { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeAddress2 { get; set; }
        public System.DateTime Birthdate { get; set; }
        public System.DateTime HiringDate { get; set; }
        public string Natinality { get; set; }
        public long Job_Id { get; set; }
        public long Department_Id { get; set; }
        public int Gender { get; set; }
        public System.DateTime Last_Modified_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int IsDeleted { get; set; }
        public long Last_Modified_User { get; set; }
        public long Branch_Id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Department Department { get; set; }
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndSalary> EndSalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryTransaction> SalaryTransactions { get; set; }
    }
}
