//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRays
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndSalary
    {
        public long EndSalaryId { get; set; }
        public long Id_Employee { get; set; }
        public int PaidHolidays { get; set; }
        public decimal Bonus { get; set; }
        public decimal Cut { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public long Last_Modified_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Last_Modified_Date { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
