//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRays
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nationality
    {
        public int Id { get; set; }
        public int National_Code { get; set; }
        public string National_Name { get; set; }
        public int IsDeleted { get; set; }
    }
}
