//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRays
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafeHouse
    {
        public long SafehouseId { get; set; }
        public System.DateTime Last_Modified_Date { get; set; }
        public System.DateTime Create_Date { get; set; }
        public int IsDeleted { get; set; }
        public long Last_Modified_User { get; set; }
        public decimal FirstPeriodCredit { get; set; }
        public decimal SalesInvoiceNetTotal { get; set; }
        public decimal PurchaseInvoiceNetTotal { get; set; }
        public decimal CmpanyExpenses { get; set; }
        public decimal DisposalDocumentAmount { get; set; }
        public decimal BillDocumentAmount { get; set; }
    
        public virtual User User { get; set; }
    }
}
