//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRays
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoiceDetail
    {
        public long InvoiceDetailsId { get; set; }
        public long TypeInvoice_Id { get; set; }
        public decimal Quantity { get; set; }
        public decimal TotalProduct { get; set; }
        public long SalesInvoice_Id { get; set; }
        public long Product_Id { get; set; }
        public System.DateTime Last_Modified_Date { get; set; }
        public System.DateTime Create_Date { get; set; }
        public int IsDeleted { get; set; }
        public long Last_Modified_User { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
        public virtual TypeInvoice TypeInvoice { get; set; }
        public virtual User User { get; set; }
    }
}
